wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1674663812.212515
    t:
      1:
      - 1
      - 41
      - 43
      - 55
      2:
      - 1
      - 41
      - 43
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.8.15
      5: 0.13.9
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: Detectron2
dataset:
  desc: null
  value: sb_train
epochs:
  desc: null
  value: 1000
learning_rate:
  desc: null
  value: 0.00025
